//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMPEMASA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depositos
    {
        public int Id { get; set; }
        public int IdVenta { get; set; }
        public int IdDepositoTipo { get; set; }
        public int IdCuenta { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual DepositoTipos DepositoTipos { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
