//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMPEMASA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IMPEMASAEntities : DbContext
    {
        public IMPEMASAEntities()
            : base("name=IMPEMASAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<DepositoTipos> DepositoTipos { get; set; }
        public virtual DbSet<VentaTipos> VentaTipos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<Depositos> Depositos { get; set; }
        public virtual DbSet<Autorizados> Autorizados { get; set; }
    
        public virtual ObjectResult<ReporteBalanceAntiguedad_Result> ReporteBalanceAntiguedad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReporteBalanceAntiguedad_Result>("ReporteBalanceAntiguedad");
        }
    }
}
